### PR TITLE
Added support for running sql scripts & deploying dacpacs

### PR DESCRIPTION
**Pull request by andyfenna**

### CODE REVIEW

**Comment by andyfenna** [comment]
Please can you merge once I have completed the WIKI?

**Comment by haf** [comment]
I'll merge after wiki and tests have been written.

**Comment by andyfenna** [comment]
how do I run these test on my local machine, and what test runner do you use etc?

**Comment by andyfenna** [comment]
Also the exe's that the new tasks run are windows binaries, and they are only windows compatible. Is Travis CI running on a windows box so that I can call the exe's that I will put in the "Albacore\spec\support\<exe>\" folders retrospectfully.

Or should I write the tests without invoking the exes. Just asset that the parameters etc are set.

**Comment by haf** [comment]
`bundle exec rake spec`

**Comment by andyfenna** [comment]
Please can you merge and create a new version?

**Comment by haf** [comment]
Where are the tests?

**Pull request closed without merging**
