### PR TITLE
Sql feature

### PR DESCRIPTION
**Pull request by andyfenna**

### CODE REVIEW

**Comment by haf** [comment]
Excellent, that's really close. I suppose you can look at the other file system tests that use the 'replace separators' function, and do the same for yours?

**Comment by haf** [comment]
I think that this change will just break it on Windows, no?

**Comment by andyfenna** [comment]
Yeah thats right, i've just pushed again, hopefully this time the test will pass.

**Comment by andyfenna** [comment]
Ready to merge?

**Comment by andyfenna** [comment]
Can you please release a new version with these changes?

**Pull request merged**
