### PR TITLE
Add ability to disable nuget's package analysis

### PR DESCRIPTION
**Pull request by jonathanmorley**
This is useful for Octopus Deploy packages, cuts down on logging output

### CODE REVIEW

**Comment by haf** [comment]
Doesn't this interfere with albacore picking the path of the nuget from the output?

**Comment by jonathanmorley** [comment]
Not sure which fetaure you mean. This should just add a parameter to the nuget pack command.

**Comment by haf** [comment]
I mean this line https://github.com/jonathanmorley/albacore/blob/feature/nuget-pack-analysis/lib/albacore/task_types/nugets_pack.rb#L78

**Comment by haf** [comment]
Ping, also; rebase needed

**Comment by haf** [comment]
Ping

**Comment by jonathanmorley** [comment]
Apologies, need to find time to get back on this

**Comment by jonathanmorley** [comment]
The `Successfully created ...` line is still present in the output

**Comment by haf** [comment]
Ok?

**Comment by jonathanmorley** [comment]
To clarify, when run in DEBUG, I can see that the package location still gets correctly picked up by albacore from the nuget pack output, with or without this flag enabled.

**Comment by haf** [comment]
Thanks!

**Pull request merged**
