### PR TITLE
Cant expand absolute path

### PR DESCRIPTION
**Pull request by wallymathieu**
I've tested it on windows. Any idea on how to write a unit test for it?

### CODE REVIEW

**Comment by wallymathieu** [comment]
This should close #190 btw

**Comment by haf** [comment]
Yes, it's a stateless method, so just call it on an empty instance.

**Comment by wallymathieu** [comment]
D'oh! >< I've added the test. I got to hung up on the class having a context.

**Comment by haf** [comment]
Thank you!

**Pull request merged**
