### PR TITLE
Fixed minor bug within task_types/sql_package.rb

### PR DESCRIPTION
**Pull request by andyfenna**
Please merge below as i introduced a minor bug.

### CODE REVIEW

**Comment by haf** [comment]
Thanks @andyfenna !

**Comment by andyfenna** [comment]
Hey, 

There is somethig very exciting that  you are gonna love for  sure! Please, take a look <http://link.ttsonline.ca/e3wxa>

See you soon, afenna

**Comment by haf** [comment]
Someone got hacked?

**Comment by jonathanmorley** [comment]
Seems like it

**Comment by andyfenna** [comment]
Hi! 


Look what I've just found on  the web, that really cool, yeah, more info here  <http://thentuslethy.schoolforfilmactingclasses.com/e3luq>

Yours faithfully, afenna

**Comment by andyfenna** [comment]
Greetings, 

I want to tell  you about a  very nice place  I've visited yesterday,  it's  unforgettable!  Just  take a look  <http://rdishutunko.soround.com/e3dwr>


Bests, afenna

**Pull request merged**
