### PR TITLE
Find msbuild.exe in new location #126

### LINKED ISSUE #126: [build] Albacore 2.0.5 build task doesn't find MSBuild 12
I'm trying to compile a Visual Studio 2013 project which requires MSBuild 12, and it looks like Albacore's build task isn't picking up the proper version of MSBuild.

I think this is because the build task doesn't look in the new location for 2013 binaries (C:\Program Files\MSBuild\12.0\Bin), as per the MSDN blog post [here](http://blogs.msdn.com/b/visualstudio/archive/2013/07/24/msbuild-is-now-part-of-visual-studio.aspx).

Am I missing something, or is this a behavior that needs updating?

### PR DESCRIPTION
**Pull request by devployment**
Pullrequest fixes  #126. Trying to read the msbuild.exe locations from registry instead of folder based look-up to have a consistent look-up strategy.

### CODE REVIEW

**Comment by haf** [comment]
Ping and happy new year! Long running PR coming to an end? =)

**Comment by devployment** [comment]
Oh darn. That's indeed long running. :) But happy new year as well.
Just committed the minor changes I made. It's checking against the proposed MSBuildToolsPath key.
Checked it now on several machines including my new DEV machine. Found no intallatin that caused issues. Happy to merge if you are. :)

**Comment by haf** [comment]
Excellent ;)

**Comment by briandonahue** [comment]
@haf Was this merged after 2.3.14 was pushed?  Don't see it there and am itching to get this fix.  Is there a way to easily pull the latest source in for stuff like this.  I am not a gems expert :)

Thanks!

**Comment by haf** [comment]
Released v2.3.15

**Comment by haf** [comment]
Here's what you specify in your gemfile to fetch directly from this repository:

``` bash
gem 'albacore', :git => 'https://github.com/Albacore/albacore.git'
```


http://bundler.io/git.html

**Comment by briandonahue** [comment]
Thanks!  I think maybe I spoke too soon anyway.  I think it may be an x64 issue or something, as t doesn't seem to hit the changed logic.  Running form Git Bash shell.

**Comment by briandonahue** [comment]
oh, awesome - great to know about retrieving from source!

**Comment by haf** [comment]
cheers

**Pull request merged**
